//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enrollment()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int id { get; set; }
        public int studentid { get; set; }
        public int classid { get; set; }
        public System.DateTime date { get; set; }
        public int createdby { get; set; }
        public string paymentdone { get; set; }
    
        public virtual ClassRoom ClassRoom { get; set; }
        public virtual Student Student { get; set; }
        public virtual UserData UserData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
