//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellingItemInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SellingItemInvoice()
        {
            this.SellingItemInvoiceDetails = new HashSet<SellingItemInvoiceDetail>();
        }
    
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string description { get; set; }
        public decimal amount { get; set; }
        public string paytype { get; set; }
        public int createdby { get; set; }
    
        public virtual UserData UserData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellingItemInvoiceDetail> SellingItemInvoiceDetails { get; set; }
    }
}
