//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellingItemInvoiceDetail
    {
        public int id { get; set; }
        public int sellingiteminvoiceid { get; set; }
        public int sellingitemid { get; set; }
        public decimal rate { get; set; }
        public int qty { get; set; }
    
        public virtual SellingItem SellingItem { get; set; }
        public virtual SellingItemInvoice SellingItemInvoice { get; set; }
    }
}
