//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttendance
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string inout { get; set; }
        public int studentid { get; set; }
        public int createdby { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual UserData UserData { get; set; }
    }
}
